GET http://localhost:3000/api/enderecos

###

POST http://localhost:3000/api/enderecos
Content-Type: application/json

{
    "rua": 59,
    "coluna": 2,
    "nivel": 1,
    "capacidadeMaxima":100
}

###

PATCH http://localhost:3000/api/enderecos/13
Content-Type: application/json

{
    "rua": 8,
    "coluna": 3,
    "nivel": 2,
    "capacidadeMaxima":100
}

###

DELETE http://localhost:3000/api/enderecos/13

###