@token= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzgzNzI4NjA3LCJleHAiOjE3ODM3NTc0MDd9.iUsI2EMCqnI42glJHcnJc0cNfeueLMMskjW7Aufm2Fg


GET http://localhost:3000/api/enderecos
Authorization: Bearer {{token}}

###

POST http://localhost:3000/api/enderecos
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "rua": 59,
    "estante": "A"
}

###

PATCH http://localhost:3000/api/enderecos/13
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "rua": 59,
    "estante": "B"
}

###

DELETE http://localhost:3000/api/enderecos/13
Authorization: Bearer {{token}}
###