

### Buscar Todos
GET http://localhost:3000/api/usuarios
###



### atualizar 
PUT http://localhost:3000/api/usuarios
Content-Type: application/json

{
  {
  "nome": "João Silva",
  "email": "joao@email.com",
  "senha": "123456",
  "role": "OPERADOR",
  "ativo": true
}
}


### deletar
DELETE http://localhost:3000/api/usuarios/5